# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - '*'

variables:
  buildConfiguration: 'Release'

stages:
  - stage: 'Build'
    displayName: 'Build the web application'
    jobs:
      - job: 'Build'
        displayName: 'Build job'
        pool:
          vmImage: ubuntu-latest

        steps:
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(build.sourcesDirectory)'
              includeRootFolder: false
          - task: PublishBuildArtifacts@1

  - stage: 'Deploy'
    displayName: 'Deploy the website'
    jobs:
      - job: 'Build'
        displayName: 'Deploy job'
        pool:
          vmImage: ubuntu-latest

        steps:
          - task: FtpUpload@2
            inputs:
              credentialsOption: 'inputs'
              serverUrl: 'ftp://ftp.ostapko.webd.pro'
              username: 'mateusz@ostapko.com'
              password: 'mateusz123!'
              rootDirectory: './'
              filePatterns: '*.html'
              remoteDirectory: './'
              clean: true
              preservePaths: true
              trustSSL: false